#-------------------------------------------------
#
# Project created by QtCreator 2017-07-28T13:41:54
#
#-------------------------------------------------

QT       -= core gui

TARGET = QNestopia
TEMPLATE = app

#RC_ICONS = $$PWD/win32/resource/application.ico

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

DEFINES += _UNICODE

# Windows SDK(v7.1A)
INCLUDEPATH += $$PWD/sdk/sdk_win/include
LIBS        += -L$$PWD/sdk/sdk_win/lib/x86
LIBS        += user32.lib ole32.lib gdi32.lib comdlg32.lib oleaut32.lib advapi32.lib ole32.lib gdi32.lib comdlg32.lib oleaut32.lib advapi32.lib

# For DirectX9.0C SDK
INCLUDEPATH += $$PWD/sdk/sdk_dx/include
LIBS        += -L$$PWD/sdk/sdk_dx/lib/x86

LIBS        += -L$$PWD/lib zlibstat.lib

RC_FILE += source/win32/resource/QNestopia.rc

CONFIG += static

QMAKE_CFLAGS_RELEASE    -= -MD
QMAKE_CFLAGS_DEBUG      -= -MDd
QMAKE_CXXFLAGS_RELEASE  -= -MD
QMAKE_CXXFLAGS_DEBUG    -= -MDd

QMAKE_CFLAGS_RELEASE    += -MT
QMAKE_CFLAGS_DEBUG      += -MTd
QMAKE_CXXFLAGS_RELEASE  += -MT
QMAKE_CXXFLAGS_DEBUG    += -MTd

# Output CFLAGS/CXXFLAGS for project file debug
#message("QMAKE_CFLAGS_RELEASE   : $$QMAKE_CFLAGS_RELEASE");
#message("QMAKE_CFLAGS_DEBUG     : $$QMAKE_CFLAGS_DEBUG");
#message("QMAKE_CXXFLAGS_RELEASE : $$QMAKE_CXXFLAGS_RELEASE");
#message("QMAKE_CXXFLAGS_DEBUG   : $$QMAKE_CXXFLAGS_DEBUG");


SOURCES += \
    source/core/api/NstApiBarcodeReader.cpp \
    source/core/api/NstApiCartridge.cpp \
    source/core/api/NstApiCheats.cpp \
    source/core/api/NstApiDipSwitches.cpp \
    source/core/api/NstApiEmulator.cpp \
    source/core/api/NstApiFds.cpp \
    source/core/api/NstApiInput.cpp \
    source/core/api/NstApiMachine.cpp \
    source/core/api/NstApiMovie.cpp \
    source/core/api/NstApiNsf.cpp \
    source/core/api/NstApiRewinder.cpp \
    source/core/api/NstApiSound.cpp \
    source/core/api/NstApiTapeRecorder.cpp \
    source/core/api/NstApiUser.cpp \
    source/core/api/NstApiVideo.cpp \
    source/core/board/NstBoard.cpp \
    source/core/board/NstBoardAe.cpp \
    source/core/board/NstBoardAgci.cpp \
    source/core/board/NstBoardAveD1012.cpp \
    source/core/board/NstBoardAveNina.cpp \
    source/core/board/NstBoardAxRom.cpp \
    source/core/board/NstBoardBandai24c0x.cpp \
    source/core/board/NstBoardBandaiAerobicsStudio.cpp \
    source/core/board/NstBoardBandaiDatach.cpp \
    source/core/board/NstBoardBandaiKaraokeStudio.cpp \
    source/core/board/NstBoardBandaiLz93d50.cpp \
    source/core/board/NstBoardBandaiLz93d50ex.cpp \
    source/core/board/NstBoardBandaiOekaKids.cpp \
    source/core/board/NstBoardBenshengBs5.cpp \
    source/core/board/NstBoardBmc110in1.cpp \
    source/core/board/NstBoardBmc1200in1.cpp \
    source/core/board/NstBoardBmc150in1.cpp \
    source/core/board/NstBoardBmc15in1.cpp \
    source/core/board/NstBoardBmc20in1.cpp \
    source/core/board/NstBoardBmc21in1.cpp \
    source/core/board/NstBoardBmc22Games.cpp \
    source/core/board/NstBoardBmc31in1.cpp \
    source/core/board/NstBoardBmc35in1.cpp \
    source/core/board/NstBoardBmc36in1.cpp \
    source/core/board/NstBoardBmc64in1.cpp \
    source/core/board/NstBoardBmc72in1.cpp \
    source/core/board/NstBoardBmc76in1.cpp \
    source/core/board/NstBoardBmc800in1.cpp \
    source/core/board/NstBoardBmc8157.cpp \
    source/core/board/NstBoardBmc9999999in1.cpp \
    source/core/board/NstBoardBmcA65as.cpp \
    source/core/board/NstBoardBmcBallgames11in1.cpp \
    source/core/board/NstBoardBmcCh001.cpp \
    source/core/board/NstBoardBmcCtc65.cpp \
    source/core/board/NstBoardBmcFamily4646B.cpp \
    source/core/board/NstBoardBmcFk23c.cpp \
    source/core/board/NstBoardBmcGamestarA.cpp \
    source/core/board/NstBoardBmcGamestarB.cpp \
    source/core/board/NstBoardBmcGolden190in1.cpp \
    source/core/board/NstBoardBmcGoldenCard6in1.cpp \
    source/core/board/NstBoardBmcGoldenGame260in1.cpp \
    source/core/board/NstBoardBmcHero.cpp \
    source/core/board/NstBoardBmcMarioParty7in1.cpp \
    source/core/board/NstBoardBmcNovelDiamond.cpp \
    source/core/board/NstBoardBmcPowerjoy84in1.cpp \
    source/core/board/NstBoardBmcResetBased4in1.cpp \
    source/core/board/NstBoardBmcSuper22Games.cpp \
    source/core/board/NstBoardBmcSuper24in1.cpp \
    source/core/board/NstBoardBmcSuper40in1.cpp \
    source/core/board/NstBoardBmcSuper700in1.cpp \
    source/core/board/NstBoardBmcSuperBig7in1.cpp \
    source/core/board/NstBoardBmcSuperGun20in1.cpp \
    source/core/board/NstBoardBmcSuperHiK300in1.cpp \
    source/core/board/NstBoardBmcSuperHiK4in1.cpp \
    source/core/board/NstBoardBmcSuperVision16in1.cpp \
    source/core/board/NstBoardBmcT262.cpp \
    source/core/board/NstBoardBmcVrc4.cpp \
    source/core/board/NstBoardBmcVt5201.cpp \
    source/core/board/NstBoardBmcY2k64in1.cpp \
    source/core/board/NstBoardBtl2708.cpp \
    source/core/board/NstBoardBtl6035052.cpp \
    source/core/board/NstBoardBtlAx5705.cpp \
    source/core/board/NstBoardBtlDragonNinja.cpp \
    source/core/board/NstBoardBtlGeniusMerioBros.cpp \
    source/core/board/NstBoardBtlMarioBaby.cpp \
    source/core/board/NstBoardBtlPikachuY2k.cpp \
    source/core/board/NstBoardBtlShuiGuanPipe.cpp \
    source/core/board/NstBoardBtlSmb2a.cpp \
    source/core/board/NstBoardBtlSmb2b.cpp \
    source/core/board/NstBoardBtlSmb2c.cpp \
    source/core/board/NstBoardBtlSmb3.cpp \
    source/core/board/NstBoardBtlSuperBros11.cpp \
    source/core/board/NstBoardBtlT230.cpp \
    source/core/board/NstBoardBtlTobidaseDaisakusen.cpp \
    source/core/board/NstBoardBxRom.cpp \
    source/core/board/NstBoardCaltron.cpp \
    source/core/board/NstBoardCamerica.cpp \
    source/core/board/NstBoardCneDecathlon.cpp \
    source/core/board/NstBoardCnePsb.cpp \
    source/core/board/NstBoardCneShlz.cpp \
    source/core/board/NstBoardCony.cpp \
    source/core/board/NstBoardCxRom.cpp \
    source/core/board/NstBoardDiscrete.cpp \
    source/core/board/NstBoardDreamtech.cpp \
    source/core/board/NstBoardEvent.cpp \
    source/core/board/NstBoardFb.cpp \
    source/core/board/NstBoardFfe.cpp \
    source/core/board/NstBoardFujiya.cpp \
    source/core/board/NstBoardFukutake.cpp \
    source/core/board/NstBoardFutureMedia.cpp \
    source/core/board/NstBoardGouder.cpp \
    source/core/board/NstBoardGxRom.cpp \
    source/core/board/NstBoardHenggedianzi.cpp \
    source/core/board/NstBoardHes.cpp \
    source/core/board/NstBoardHosenkan.cpp \
    source/core/board/NstBoardIremG101.cpp \
    source/core/board/NstBoardIremH3001.cpp \
    source/core/board/NstBoardIremHolyDiver.cpp \
    source/core/board/NstBoardIremKaiketsu.cpp \
    source/core/board/NstBoardIremLrog017.cpp \
    source/core/board/NstBoardJalecoJf11.cpp \
    source/core/board/NstBoardJalecoJf13.cpp \
    source/core/board/NstBoardJalecoJf16.cpp \
    source/core/board/NstBoardJalecoJf17.cpp \
    source/core/board/NstBoardJalecoJf19.cpp \
    source/core/board/NstBoardJalecoSs88006.cpp \
    source/core/board/NstBoardJyCompany.cpp \
    source/core/board/NstBoardKaiser.cpp \
    source/core/board/NstBoardKasing.cpp \
    source/core/board/NstBoardKayH2288.cpp \
    source/core/board/NstBoardKayPandaPrince.cpp \
    source/core/board/NstBoardKonamiVrc1.cpp \
    source/core/board/NstBoardKonamiVrc2.cpp \
    source/core/board/NstBoardKonamiVrc3.cpp \
    source/core/board/NstBoardKonamiVrc4.cpp \
    source/core/board/NstBoardKonamiVrc6.cpp \
    source/core/board/NstBoardKonamiVrc7.cpp \
    source/core/board/NstBoardKonamiVsSystem.cpp \
    source/core/board/NstBoardMagicSeries.cpp \
    source/core/board/NstBoardMmc1.cpp \
    source/core/board/NstBoardMmc2.cpp \
    source/core/board/NstBoardMmc3.cpp \
    source/core/board/NstBoardMmc4.cpp \
    source/core/board/NstBoardMmc5.cpp \
    source/core/board/NstBoardMmc6.cpp \
    source/core/board/NstBoardNamcot163.cpp \
    source/core/board/NstBoardNamcot34xx.cpp \
    source/core/board/NstBoardNanjing.cpp \
    source/core/board/NstBoardNihon.cpp \
    source/core/board/NstBoardNitra.cpp \
    source/core/board/NstBoardNtdec.cpp \
    source/core/board/NstBoardOpenCorp.cpp \
    source/core/board/NstBoardQj.cpp \
    source/core/board/NstBoardRcm.cpp \
    source/core/board/NstBoardRexSoftDb5z.cpp \
    source/core/board/NstBoardRexSoftSl1632.cpp \
    source/core/board/NstBoardRumbleStation.cpp \
    source/core/board/NstBoardSachen74x374.cpp \
    source/core/board/NstBoardSachenS8259.cpp \
    source/core/board/NstBoardSachenSa0036.cpp \
    source/core/board/NstBoardSachenSa0037.cpp \
    source/core/board/NstBoardSachenSa72007.cpp \
    source/core/board/NstBoardSachenSa72008.cpp \
    source/core/board/NstBoardSachenStreetHeroes.cpp \
    source/core/board/NstBoardSachenTca01.cpp \
    source/core/board/NstBoardSachenTcu.cpp \
    source/core/board/NstBoardSomeriTeamSl12.cpp \
    source/core/board/NstBoardSubor.cpp \
    source/core/board/NstBoardSunsoft1.cpp \
    source/core/board/NstBoardSunsoft2.cpp \
    source/core/board/NstBoardSunsoft3.cpp \
    source/core/board/NstBoardSunsoft4.cpp \
    source/core/board/NstBoardSunsoft5b.cpp \
    source/core/board/NstBoardSunsoftDcs.cpp \
    source/core/board/NstBoardSunsoftFme7.cpp \
    source/core/board/NstBoardSuperGameBoogerman.cpp \
    source/core/board/NstBoardSuperGameLionKing.cpp \
    source/core/board/NstBoardSuperGamePocahontas2.cpp \
    source/core/board/NstBoardTaitoTc0190fmc.cpp \
    source/core/board/NstBoardTaitoTc0190fmcPal16r4.cpp \
    source/core/board/NstBoardTaitoX1005.cpp \
    source/core/board/NstBoardTaitoX1017.cpp \
    source/core/board/NstBoardTengen.cpp \
    source/core/board/NstBoardTengenRambo1.cpp \
    source/core/board/NstBoardTxc.cpp \
    source/core/board/NstBoardTxcMxmdhtwo.cpp \
    source/core/board/NstBoardTxcPoliceman.cpp \
    source/core/board/NstBoardTxcTw.cpp \
    source/core/board/NstBoardTxRom.cpp \
    source/core/board/NstBoardUnlA9746.cpp \
    source/core/board/NstBoardUnlCc21.cpp \
    source/core/board/NstBoardUnlEdu2000.cpp \
    source/core/board/NstBoardUnlKingOfFighters96.cpp \
    source/core/board/NstBoardUnlKingOfFighters97.cpp \
    source/core/board/NstBoardUnlMortalKombat2.cpp \
    source/core/board/NstBoardUnlN625092.cpp \
    source/core/board/NstBoardUnlSuperFighter3.cpp \
    source/core/board/NstBoardUnlTf1201.cpp \
    source/core/board/NstBoardUnlWorldHero.cpp \
    source/core/board/NstBoardUnlXzy.cpp \
    source/core/board/NstBoardUxRom.cpp \
    source/core/board/NstBoardVsSystem.cpp \
    source/core/board/NstBoardWaixing.cpp \
    source/core/board/NstBoardWaixingFfv.cpp \
    source/core/board/NstBoardWaixingPs2.cpp \
    source/core/board/NstBoardWaixingSecurity.cpp \
    source/core/board/NstBoardWaixingSgz.cpp \
    source/core/board/NstBoardWaixingSgzlz.cpp \
    source/core/board/NstBoardWaixingSh2.cpp \
    source/core/board/NstBoardWaixingZs.cpp \
    source/core/board/NstBoardWhirlwind.cpp \
    source/core/board/NstBoardZz.cpp \
    source/core/input/NstInpAdapter.cpp \
    source/core/input/NstInpBandaiHyperShot.cpp \
    source/core/input/NstInpBarcodeWorld.cpp \
    source/core/input/NstInpCrazyClimber.cpp \
    source/core/input/NstInpDoremikkoKeyboard.cpp \
    source/core/input/NstInpExcitingBoxing.cpp \
    source/core/input/NstInpFamilyKeyboard.cpp \
    source/core/input/NstInpFamilyTrainer.cpp \
    source/core/input/NstInpHoriTrack.cpp \
    source/core/input/NstInpKonamiHyperShot.cpp \
    source/core/input/NstInpMahjong.cpp \
    source/core/input/NstInpMouse.cpp \
    source/core/input/NstInpOekaKidsTablet.cpp \
    source/core/input/NstInpPachinko.cpp \
    source/core/input/NstInpPad.cpp \
    source/core/input/NstInpPaddle.cpp \
    source/core/input/NstInpPartyTap.cpp \
    source/core/input/NstInpPokkunMoguraa.cpp \
    source/core/input/NstInpPowerGlove.cpp \
    source/core/input/NstInpPowerPad.cpp \
    source/core/input/NstInpRob.cpp \
    source/core/input/NstInpSuborKeyboard.cpp \
    source/core/input/NstInpTopRider.cpp \
    source/core/input/NstInpTurboFile.cpp \
    source/core/input/NstInpZapper.cpp \
    source/core/vssystem/NstVsRbiBaseball.cpp \
    source/core/vssystem/NstVsSuperXevious.cpp \
    source/core/vssystem/NstVsSystem.cpp \
    source/core/vssystem/NstVsTkoBoxing.cpp \
    source/core/NstApu.cpp \
    source/core/NstAssert.cpp \
    source/core/NstCartridge.cpp \
    source/core/NstCartridgeInes.cpp \
    source/core/NstCartridgeRomset.cpp \
    source/core/NstCartridgeUnif.cpp \
    source/core/NstCheats.cpp \
    source/core/NstChecksum.cpp \
    source/core/NstChips.cpp \
    source/core/NstCore.cpp \
    source/core/NstCpu.cpp \
    source/core/NstCrc32.cpp \
    source/core/NstFds.cpp \
    source/core/NstFile.cpp \
    source/core/NstImage.cpp \
    source/core/NstImageDatabase.cpp \
    source/core/NstLog.cpp \
    source/core/NstMachine.cpp \
    source/core/NstMemory.cpp \
    source/core/NstNsf.cpp \
    source/core/NstPatcher.cpp \
    source/core/NstPatcherIps.cpp \
    source/core/NstPatcherUps.cpp \
    source/core/NstPins.cpp \
    source/core/NstPpu.cpp \
    source/core/NstProperties.cpp \
    source/core/NstRam.cpp \
    source/core/NstSha1.cpp \
    source/core/NstSoundPcm.cpp \
    source/core/NstSoundPlayer.cpp \
    source/core/NstSoundRenderer.cpp \
    source/core/NstSoundRenderer.inl \
    source/core/NstState.cpp \
    source/core/NstStream.cpp \
    source/core/NstTracker.cpp \
    source/core/NstTrackerMovie.cpp \
    source/core/NstTrackerRewinder.cpp \
    source/core/NstVector.cpp \
    source/core/NstVideoFilter2xSaI.cpp \
    source/core/NstVideoFilterHq2x.inl \
    source/core/NstVideoFilterHq3x.inl \
    source/core/NstVideoFilterHq4x.inl \
    source/core/NstVideoFilterHqX.cpp \
    source/core/NstVideoFilterNone.cpp \
    source/core/NstVideoFilterNtsc.cpp \
    source/core/NstVideoFilterScaleX.cpp \
    source/core/NstVideoRenderer.cpp \
    source/core/NstVideoScreen.cpp \
    source/core/NstXml.cpp \
    source/core/NstZlib.cpp \
    source/core/NstVideoFilterNtscCfg.c \
    source/nes_ntsc/nes_ntsc.inl \
    source/win32/NstApplicationConfiguration.cpp \
    source/win32/NstApplicationException.cpp \
    source/win32/NstApplicationInstance.cpp \
    source/win32/NstApplicationLanguage.cpp \
    source/win32/NstApplicationMain.cpp \
    source/win32/NstCollectionRouter.inl \
    source/win32/NstCollectionVector.cpp \
    source/win32/NstCtrlCheckBox.cpp \
    source/win32/NstCtrlComboBox.cpp \
    source/win32/NstCtrlEdit.cpp \
    source/win32/NstCtrlListBox.cpp \
    source/win32/NstCtrlListView.cpp \
    source/win32/NstCtrlSlider.cpp \
    source/win32/NstCtrlStandard.cpp \
    source/win32/NstCtrlTreeView.cpp \
    source/win32/NstDialogAbout.cpp \
    source/win32/NstDialogAutoSaver.cpp \
    source/win32/NstDialogBarcodeReader.cpp \
    source/win32/NstDialogBrowse.cpp \
    source/win32/NstDialogCheats.cpp \
    source/win32/NstDialogDipSwitches.cpp \
    source/win32/NstDialogFds.cpp \
    source/win32/NstDialogFind.cpp \
    source/win32/NstDialogFrameClock.cpp \
    source/win32/NstDialogImageDatabase.cpp \
    source/win32/NstDialogImageInfo.cpp \
    source/win32/NstDialogInesHeader.cpp \
    source/win32/NstDialogInput.cpp \
    source/win32/NstDialogLanguage.cpp \
    source/win32/NstDialogLauncher.cpp \
    source/win32/NstDialogLauncherColors.cpp \
    source/win32/NstDialogLauncherColumns.cpp \
    source/win32/NstDialogLauncherFiles.cpp \
    source/win32/NstDialogLauncherFileTable.cpp \
    source/win32/NstDialogLauncherList.cpp \
    source/win32/NstDialogLauncherPaths.cpp \
    source/win32/NstDialogLauncherTree.cpp \
    source/win32/NstDialogLicense.cpp \
    source/win32/NstDialogLogfile.cpp \
    source/win32/NstDialogMovie.cpp \
    source/win32/NstDialogNetPlay.cpp \
    source/win32/NstDialogNetplayChat.cpp \
    source/win32/NstDialogPaletteEditor.cpp \
    source/win32/NstDialogPaths.cpp \
    source/win32/NstDialogPreferences.cpp \
    source/win32/NstDialogSound.cpp \
    source/win32/NstDialogTapeRecorder.cpp \
    source/win32/NstDialogVideo.cpp \
    source/win32/NstDialogVideoDecoder.cpp \
    source/win32/NstDialogVideoFilters.cpp \
    source/win32/NstDirect2D.cpp \
    source/win32/NstDirectInput.cpp \
    source/win32/NstDirectSound.cpp \
    source/win32/NstIoArchive.cpp \
    source/win32/NstIoFile.cpp \
    source/win32/NstIoLog.cpp \
    source/win32/NstIoScreen.cpp \
    source/win32/NstIoStream.cpp \
    source/win32/NstIoWave.cpp \
    source/win32/NstMain.cpp \
    source/win32/NstManager.cpp \
    source/win32/NstManagerAviConverter.cpp \
    source/win32/NstManagerBarcodeReader.cpp \
    source/win32/NstManagerCheats.cpp \
    source/win32/NstManagerDipSwitches.cpp \
    source/win32/NstManagerEmulator.cpp \
    source/win32/NstManagerFds.cpp \
    source/win32/NstManagerFiles.cpp \
    source/win32/NstManagerFrameClock.cpp \
    source/win32/NstManagerHelp.cpp \
    source/win32/NstManagerImageDatabase.cpp \
    source/win32/NstManagerImageInfo.cpp \
    source/win32/NstManagerInesHeader.cpp \
    source/win32/NstManagerInput.cpp \
    source/win32/NstManagerInputClipboard.cpp \
    source/win32/NstManagerInputCommands.cpp \
    source/win32/NstManagerInputCursor.cpp \
    source/win32/NstManagerLanguage.cpp \
    source/win32/NstManagerLauncher.cpp \
    source/win32/NstManagerLogfile.cpp \
    source/win32/NstManagerMachine.cpp \
    source/win32/NstManagerMovie.cpp \
    source/win32/NstManagerNetplay.cpp \
    source/win32/NstManagerNsf.cpp \
    source/win32/NstManagerPaths.cpp \
    source/win32/NstManagerPathsFilter.cpp \
    source/win32/NstManagerPreferences.cpp \
    source/win32/NstManagerRecentDirs.cpp \
    source/win32/NstManagerRecentFiles.cpp \
    source/win32/NstManagerSaveStates.cpp \
    source/win32/NstManagerSound.cpp \
    source/win32/NstManagerSoundRecorder.cpp \
    source/win32/NstManagerTapeRecorder.cpp \
    source/win32/NstManagerVideo.cpp \
    source/win32/NstResourceBitmap.cpp \
    source/win32/NstResourceClipboard.cpp \
    source/win32/NstResourceCursor.cpp \
    source/win32/NstResourceFile.cpp \
    source/win32/NstResourceGeneric.cpp \
    source/win32/NstResourceIcon.cpp \
    source/win32/NstResourceMenu.cpp \
    source/win32/NstResourceString.cpp \
    source/win32/NstResourceVersion.cpp \
    source/win32/NstString.cpp \
    source/win32/NstSystemAccelerator.cpp \
    source/win32/NstSystemDll.cpp \
    source/win32/NstSystemGuid.cpp \
    source/win32/NstSystemInfo.cpp \
    source/win32/NstSystemKeyboard.cpp \
    source/win32/NstSystemRegistry.cpp \
    source/win32/NstSystemThread.cpp \
    source/win32/NstSystemTime.cpp \
    source/win32/NstSystemTimer.cpp \
    source/win32/NstWindowCustom.cpp \
    source/win32/NstWindowDialog.cpp \
    source/win32/NstWindowDialog.inl \
    source/win32/NstWindowDropFiles.cpp \
    source/win32/NstWindowDynamic.cpp \
    source/win32/NstWindowGeneric.cpp \
    source/win32/NstWindowMain.cpp \
    source/win32/NstWindowMenu.cpp \
    source/win32/NstWindowParam.cpp \
    source/win32/NstWindowPoint.cpp \
    source/win32/NstWindowRect.cpp \
    source/win32/NstWindowStatusBar.cpp \
    source/win32/NstWindowUser.cpp

HEADERS  += \
    source/core/api/NstApi.hpp \
    source/core/api/NstApiBarcodeReader.hpp \
    source/core/api/NstApiCartridge.hpp \
    source/core/api/NstApiCheats.hpp \
    source/core/api/NstApiConfig.hpp \
    source/core/api/NstApiDipSwitches.hpp \
    source/core/api/NstApiEmulator.hpp \
    source/core/api/NstApiFds.hpp \
    source/core/api/NstApiInput.hpp \
    source/core/api/NstApiMachine.hpp \
    source/core/api/NstApiMovie.hpp \
    source/core/api/NstApiNsf.hpp \
    source/core/api/NstApiRewinder.hpp \
    source/core/api/NstApiSound.hpp \
    source/core/api/NstApiTapeRecorder.hpp \
    source/core/api/NstApiUser.hpp \
    source/core/api/NstApiVideo.hpp \
    source/core/board/NstBoard.hpp \
    source/core/board/NstBoardAe.hpp \
    source/core/board/NstBoardAgci.hpp \
    source/core/board/NstBoardAve.hpp \
    source/core/board/NstBoardAveD1012.hpp \
    source/core/board/NstBoardAveNina.hpp \
    source/core/board/NstBoardAxRom.hpp \
    source/core/board/NstBoardBandai.hpp \
    source/core/board/NstBoardBandai24c0x.hpp \
    source/core/board/NstBoardBandaiAerobicsStudio.hpp \
    source/core/board/NstBoardBandaiDatach.hpp \
    source/core/board/NstBoardBandaiKaraokeStudio.hpp \
    source/core/board/NstBoardBandaiLz93d50.hpp \
    source/core/board/NstBoardBandaiLz93d50ex.hpp \
    source/core/board/NstBoardBandaiOekaKids.hpp \
    source/core/board/NstBoardBenshengBs5.hpp \
    source/core/board/NstBoardBmc110in1.hpp \
    source/core/board/NstBoardBmc1200in1.hpp \
    source/core/board/NstBoardBmc150in1.hpp \
    source/core/board/NstBoardBmc15in1.hpp \
    source/core/board/NstBoardBmc20in1.hpp \
    source/core/board/NstBoardBmc21in1.hpp \
    source/core/board/NstBoardBmc22Games.hpp \
    source/core/board/NstBoardBmc31in1.hpp \
    source/core/board/NstBoardBmc35in1.hpp \
    source/core/board/NstBoardBmc36in1.hpp \
    source/core/board/NstBoardBmc64in1.hpp \
    source/core/board/NstBoardBmc72in1.hpp \
    source/core/board/NstBoardBmc76in1.hpp \
    source/core/board/NstBoardBmc800in1.hpp \
    source/core/board/NstBoardBmc8157.hpp \
    source/core/board/NstBoardBmc9999999in1.hpp \
    source/core/board/NstBoardBmcA65as.hpp \
    source/core/board/NstBoardBmcBallgames11in1.hpp \
    source/core/board/NstBoardBmcCh001.hpp \
    source/core/board/NstBoardBmcCtc65.hpp \
    source/core/board/NstBoardBmcFamily4646B.hpp \
    source/core/board/NstBoardBmcFk23c.hpp \
    source/core/board/NstBoardBmcGamestarA.hpp \
    source/core/board/NstBoardBmcGamestarB.hpp \
    source/core/board/NstBoardBmcGolden190in1.hpp \
    source/core/board/NstBoardBmcGoldenCard6in1.hpp \
    source/core/board/NstBoardBmcGoldenGame260in1.hpp \
    source/core/board/NstBoardBmcHero.hpp \
    source/core/board/NstBoardBmcMarioParty7in1.hpp \
    source/core/board/NstBoardBmcNovelDiamond.hpp \
    source/core/board/NstBoardBmcPowerjoy84in1.hpp \
    source/core/board/NstBoardBmcResetBased4in1.hpp \
    source/core/board/NstBoardBmcSuper22Games.hpp \
    source/core/board/NstBoardBmcSuper24in1.hpp \
    source/core/board/NstBoardBmcSuper40in1.hpp \
    source/core/board/NstBoardBmcSuper700in1.hpp \
    source/core/board/NstBoardBmcSuperBig7in1.hpp \
    source/core/board/NstBoardBmcSuperGun20in1.hpp \
    source/core/board/NstBoardBmcSuperHiK300in1.hpp \
    source/core/board/NstBoardBmcSuperHiK4in1.hpp \
    source/core/board/NstBoardBmcSuperVision16in1.hpp \
    source/core/board/NstBoardBmcT262.hpp \
    source/core/board/NstBoardBmcVrc4.hpp \
    source/core/board/NstBoardBmcVt5201.hpp \
    source/core/board/NstBoardBmcY2k64in1.hpp \
    source/core/board/NstBoardBtl2708.hpp \
    source/core/board/NstBoardBtl6035052.hpp \
    source/core/board/NstBoardBtlAx5705.hpp \
    source/core/board/NstBoardBtlDragonNinja.hpp \
    source/core/board/NstBoardBtlGeniusMerioBros.hpp \
    source/core/board/NstBoardBtlMarioBaby.hpp \
    source/core/board/NstBoardBtlPikachuY2k.hpp \
    source/core/board/NstBoardBtlShuiGuanPipe.hpp \
    source/core/board/NstBoardBtlSmb2a.hpp \
    source/core/board/NstBoardBtlSmb2b.hpp \
    source/core/board/NstBoardBtlSmb2c.hpp \
    source/core/board/NstBoardBtlSmb3.hpp \
    source/core/board/NstBoardBtlSuperBros11.hpp \
    source/core/board/NstBoardBtlT230.hpp \
    source/core/board/NstBoardBtlTobidaseDaisakusen.hpp \
    source/core/board/NstBoardBxRom.hpp \
    source/core/board/NstBoardCaltron.hpp \
    source/core/board/NstBoardCamerica.hpp \
    source/core/board/NstBoardCne.hpp \
    source/core/board/NstBoardCneDecathlon.hpp \
    source/core/board/NstBoardCnePsb.hpp \
    source/core/board/NstBoardCneShlz.hpp \
    source/core/board/NstBoardCony.hpp \
    source/core/board/NstBoardCxRom.hpp \
    source/core/board/NstBoardDiscrete.hpp \
    source/core/board/NstBoardDreamtech.hpp \
    source/core/board/NstBoardDxRom.hpp \
    source/core/board/NstBoardEvent.hpp \
    source/core/board/NstBoardExRom.hpp \
    source/core/board/NstBoardFb.hpp \
    source/core/board/NstBoardFfe.hpp \
    source/core/board/NstBoardFujiya.hpp \
    source/core/board/NstBoardFukutake.hpp \
    source/core/board/NstBoardFutureMedia.hpp \
    source/core/board/NstBoardFxRom.hpp \
    source/core/board/NstBoardGouder.hpp \
    source/core/board/NstBoardGxRom.hpp \
    source/core/board/NstBoardHenggedianzi.hpp \
    source/core/board/NstBoardHes.hpp \
    source/core/board/NstBoardHosenkan.hpp \
    source/core/board/NstBoardHxRom.hpp \
    source/core/board/NstBoardIrem.hpp \
    source/core/board/NstBoardIremG101.hpp \
    source/core/board/NstBoardIremH3001.hpp \
    source/core/board/NstBoardIremHolyDiver.hpp \
    source/core/board/NstBoardIremKaiketsu.hpp \
    source/core/board/NstBoardIremLrog017.hpp \
    source/core/board/NstBoardJaleco.hpp \
    source/core/board/NstBoardJalecoJf11.hpp \
    source/core/board/NstBoardJalecoJf13.hpp \
    source/core/board/NstBoardJalecoJf16.hpp \
    source/core/board/NstBoardJalecoJf17.hpp \
    source/core/board/NstBoardJalecoJf19.hpp \
    source/core/board/NstBoardJalecoSs88006.hpp \
    source/core/board/NstBoardJxRom.hpp \
    source/core/board/NstBoardJyCompany.hpp \
    source/core/board/NstBoardKaiser.hpp \
    source/core/board/NstBoardKasing.hpp \
    source/core/board/NstBoardKay.hpp \
    source/core/board/NstBoardKayH2288.hpp \
    source/core/board/NstBoardKayPandaPrince.hpp \
    source/core/board/NstBoardKonami.hpp \
    source/core/board/NstBoardKonamiVrc1.hpp \
    source/core/board/NstBoardKonamiVrc2.hpp \
    source/core/board/NstBoardKonamiVrc3.hpp \
    source/core/board/NstBoardKonamiVrc4.hpp \
    source/core/board/NstBoardKonamiVrc6.hpp \
    source/core/board/NstBoardKonamiVrc7.hpp \
    source/core/board/NstBoardKonamiVsSystem.hpp \
    source/core/board/NstBoardMagicSeries.hpp \
    source/core/board/NstBoardMmc1.hpp \
    source/core/board/NstBoardMmc2.hpp \
    source/core/board/NstBoardMmc3.hpp \
    source/core/board/NstBoardMmc4.hpp \
    source/core/board/NstBoardMmc5.hpp \
    source/core/board/NstBoardMmc6.hpp \
    source/core/board/NstBoardMxRom.hpp \
    source/core/board/NstBoardNamcot.hpp \
    source/core/board/NstBoardNamcot163.hpp \
    source/core/board/NstBoardNamcot34xx.hpp \
    source/core/board/NstBoardNanjing.hpp \
    source/core/board/NstBoardNihon.hpp \
    source/core/board/NstBoardNitra.hpp \
    source/core/board/NstBoardNRom.hpp \
    source/core/board/NstBoardNtdec.hpp \
    source/core/board/NstBoardNxRom.hpp \
    source/core/board/NstBoardOpenCorp.hpp \
    source/core/board/NstBoardPxRom.hpp \
    source/core/board/NstBoardQj.hpp \
    source/core/board/NstBoardRcm.hpp \
    source/core/board/NstBoardRexSoft.hpp \
    source/core/board/NstBoardRexSoftDb5z.hpp \
    source/core/board/NstBoardRexSoftSl1632.hpp \
    source/core/board/NstBoardRumbleStation.hpp \
    source/core/board/NstBoardSachen.hpp \
    source/core/board/NstBoardSachen74x374.hpp \
    source/core/board/NstBoardSachenS8259.hpp \
    source/core/board/NstBoardSachenSa0036.hpp \
    source/core/board/NstBoardSachenSa0037.hpp \
    source/core/board/NstBoardSachenSa72007.hpp \
    source/core/board/NstBoardSachenSa72008.hpp \
    source/core/board/NstBoardSachenStreetHeroes.hpp \
    source/core/board/NstBoardSachenTca01.hpp \
    source/core/board/NstBoardSachenTcu.hpp \
    source/core/board/NstBoardSomeriTeam.hpp \
    source/core/board/NstBoardSomeriTeamSl12.hpp \
    source/core/board/NstBoardSubor.hpp \
    source/core/board/NstBoardSunsoft.hpp \
    source/core/board/NstBoardSunsoft1.hpp \
    source/core/board/NstBoardSunsoft2.hpp \
    source/core/board/NstBoardSunsoft3.hpp \
    source/core/board/NstBoardSunsoft4.hpp \
    source/core/board/NstBoardSunsoft5b.hpp \
    source/core/board/NstBoardSunsoftDcs.hpp \
    source/core/board/NstBoardSunsoftFme7.hpp \
    source/core/board/NstBoardSuperGame.hpp \
    source/core/board/NstBoardSuperGameBoogerman.hpp \
    source/core/board/NstBoardSuperGameLionKing.hpp \
    source/core/board/NstBoardSuperGamePocahontas2.hpp \
    source/core/board/NstBoardSxRom.hpp \
    source/core/board/NstBoardTaito.hpp \
    source/core/board/NstBoardTaitoTc0190fmc.hpp \
    source/core/board/NstBoardTaitoTc0190fmcPal16r4.hpp \
    source/core/board/NstBoardTaitoX1005.hpp \
    source/core/board/NstBoardTaitoX1017.hpp \
    source/core/board/NstBoardTengen.hpp \
    source/core/board/NstBoardTengenRambo1.hpp \
    source/core/board/NstBoardTxc.hpp \
    source/core/board/NstBoardTxcMxmdhtwo.hpp \
    source/core/board/NstBoardTxcPoliceman.hpp \
    source/core/board/NstBoardTxcTw.hpp \
    source/core/board/NstBoardTxRom.hpp \
    source/core/board/NstBoardUnlA9746.hpp \
    source/core/board/NstBoardUnlCc21.hpp \
    source/core/board/NstBoardUnlEdu2000.hpp \
    source/core/board/NstBoardUnlKingOfFighters96.hpp \
    source/core/board/NstBoardUnlKingOfFighters97.hpp \
    source/core/board/NstBoardUnlMortalKombat2.hpp \
    source/core/board/NstBoardUnlN625092.hpp \
    source/core/board/NstBoardUnlSuperFighter3.hpp \
    source/core/board/NstBoardUnlTf1201.hpp \
    source/core/board/NstBoardUnlWorldHero.hpp \
    source/core/board/NstBoardUnlXzy.hpp \
    source/core/board/NstBoardUxRom.hpp \
    source/core/board/NstBoardVsSystem.hpp \
    source/core/board/NstBoardWaixing.hpp \
    source/core/board/NstBoardWaixingFfv.hpp \
    source/core/board/NstBoardWaixingPs2.hpp \
    source/core/board/NstBoardWaixingSecurity.hpp \
    source/core/board/NstBoardWaixingSgz.hpp \
    source/core/board/NstBoardWaixingSgzlz.hpp \
    source/core/board/NstBoardWaixingSh2.hpp \
    source/core/board/NstBoardWaixingZs.hpp \
    source/core/board/NstBoardWhirlwind.hpp \
    source/core/board/NstBoardZz.hpp \
    source/core/input/NstInpAdapter.hpp \
    source/core/input/NstInpBandaiHyperShot.hpp \
    source/core/input/NstInpBarcodeWorld.hpp \
    source/core/input/NstInpCrazyClimber.hpp \
    source/core/input/NstInpDevice.hpp \
    source/core/input/NstInpDoremikkoKeyboard.hpp \
    source/core/input/NstInpExcitingBoxing.hpp \
    source/core/input/NstInpFamilyKeyboard.hpp \
    source/core/input/NstInpFamilyTrainer.hpp \
    source/core/input/NstInpHoriTrack.hpp \
    source/core/input/NstInpKonamiHyperShot.hpp \
    source/core/input/NstInpMahjong.hpp \
    source/core/input/NstInpMouse.hpp \
    source/core/input/NstInpOekaKidsTablet.hpp \
    source/core/input/NstInpPachinko.hpp \
    source/core/input/NstInpPad.hpp \
    source/core/input/NstInpPaddle.hpp \
    source/core/input/NstInpPartyTap.hpp \
    source/core/input/NstInpPokkunMoguraa.hpp \
    source/core/input/NstInpPowerGlove.hpp \
    source/core/input/NstInpPowerPad.hpp \
    source/core/input/NstInpRob.hpp \
    source/core/input/NstInpSuborKeyboard.hpp \
    source/core/input/NstInpTopRider.hpp \
    source/core/input/NstInpTurboFile.hpp \
    source/core/input/NstInpZapper.hpp \
    source/core/vssystem/NstVsRbiBaseball.hpp \
    source/core/vssystem/NstVsSuperXevious.hpp \
    source/core/vssystem/NstVsSystem.hpp \
    source/core/vssystem/NstVsTkoBoxing.hpp \
    source/core/NstApu.hpp \
    source/core/NstAssert.hpp \
    source/core/NstBarcodeReader.hpp \
    source/core/NstBase.hpp \
    source/core/NstCartridge.hpp \
    source/core/NstCartridgeInes.hpp \
    source/core/NstCartridgeRomset.hpp \
    source/core/NstCartridgeUnif.hpp \
    source/core/NstCheats.hpp \
    source/core/NstChecksum.hpp \
    source/core/NstChips.hpp \
    source/core/NstClock.hpp \
    source/core/NstCore.hpp \
    source/core/NstCpu.hpp \
    source/core/NstCrc32.hpp \
    source/core/NstDipSwitches.hpp \
    source/core/NstFds.hpp \
    source/core/NstFile.hpp \
    source/core/NstFpuPrecision.hpp \
    source/core/NstHook.hpp \
    source/core/NstImage.hpp \
    source/core/NstImageDatabase.hpp \
    source/core/NstIoAccessor.hpp \
    source/core/NstIoLine.hpp \
    source/core/NstIoMap.hpp \
    source/core/NstIoPort.hpp \
    source/core/NstLog.hpp \
    source/core/NstMachine.hpp \
    source/core/NstMemory.hpp \
    source/core/NstNsf.hpp \
    source/core/NstPatcher.hpp \
    source/core/NstPatcherIps.hpp \
    source/core/NstPatcherUps.hpp \
    source/core/NstPins.hpp \
    source/core/NstPpu.hpp \
    source/core/NstProperties.hpp \
    source/core/NstRam.hpp \
    source/core/NstSha1.hpp \
    source/core/NstSoundPcm.hpp \
    source/core/NstSoundPlayer.hpp \
    source/core/NstSoundRenderer.hpp \
    source/core/NstState.hpp \
    source/core/NstStream.hpp \
    source/core/NstTimer.hpp \
    source/core/NstTracker.hpp \
    source/core/NstTrackerMovie.hpp \
    source/core/NstTrackerRewinder.hpp \
    source/core/NstVector.hpp \
    source/core/NstVideoFilter2xSaI.hpp \
    source/core/NstVideoFilterHqX.hpp \
    source/core/NstVideoFilterNone.hpp \
    source/core/NstVideoFilterNtsc.hpp \
    source/core/NstVideoFilterScaleX.hpp \
    source/core/NstVideoRenderer.hpp \
    source/core/NstVideoScreen.hpp \
    source/core/NstXml.hpp \
    source/core/NstZlib.hpp \
    source/nes_ntsc/nes_ntsc.h \
    source/nes_ntsc/nes_ntsc_config.h \
    source/nes_ntsc/nes_ntsc_impl.h \
    source/zlib/ioapi.h \
    source/zlib/unzip.h \
    source/zlib/zconf.h \
    source/zlib/zip.h \
    source/zlib/zlib.h \
    source/win32/language/language.rc \
    source/win32/language/resource.h \
    source/win32/resource/resource.h \
    source/win32/NstApplicationConfiguration.hpp \
    source/win32/NstApplicationException.hpp \
    source/win32/NstApplicationInstance.hpp \
    source/win32/NstApplicationLanguage.hpp \
    source/win32/NstApplicationMain.hpp \
    source/win32/NstCollectionBitSet.hpp \
    source/win32/NstCollectionRouter.hpp \
    source/win32/NstCollectionVector.hpp \
    source/win32/NstCtrlCheckBox.hpp \
    source/win32/NstCtrlComboBox.hpp \
    source/win32/NstCtrlEdit.hpp \
    source/win32/NstCtrlListBox.hpp \
    source/win32/NstCtrlListView.hpp \
    source/win32/NstCtrlRadioButton.hpp \
    source/win32/NstCtrlSlider.hpp \
    source/win32/NstCtrlStandard.hpp \
    source/win32/NstCtrlTreeView.hpp \
    source/win32/NstDialogAbout.hpp \
    source/win32/NstDialogAutoSaver.hpp \
    source/win32/NstDialogBarcodeReader.hpp \
    source/win32/NstDialogBrowse.hpp \
    source/win32/NstDialogCheats.hpp \
    source/win32/NstDialogDipSwitches.hpp \
    source/win32/NstDialogFds.hpp \
    source/win32/NstDialogFind.hpp \
    source/win32/NstDialogFrameClock.hpp \
    source/win32/NstDialogImageDatabase.hpp \
    source/win32/NstDialogImageInfo.hpp \
    source/win32/NstDialogInesHeader.hpp \
    source/win32/NstDialogInput.hpp \
    source/win32/NstDialogLanguage.hpp \
    source/win32/NstDialogLauncher.hpp \
    source/win32/NstDialogLicense.hpp \
    source/win32/NstDialogLogfile.hpp \
    source/win32/NstDialogMovie.hpp \
    source/win32/NstDialogNetplay.hpp \
    source/win32/NstDialogPaletteEditor.hpp \
    source/win32/NstDialogPaths.hpp \
    source/win32/NstDialogPreferences.hpp \
    source/win32/NstDialogSound.hpp \
    source/win32/NstDialogTapeRecorder.hpp \
    source/win32/NstDialogVideo.hpp \
    source/win32/NstDialogVideoDecoder.hpp \
    source/win32/NstDialogVideoFilters.hpp \
    source/win32/NstDirect2D.hpp \
    source/win32/NstDirectInput.hpp \
    source/win32/NstDirectSound.hpp \
    source/win32/NstDirectX.hpp \
    source/win32/NstIoArchive.hpp \
    source/win32/NstIoFile.hpp \
    source/win32/NstIoLog.hpp \
    source/win32/NstIoScreen.hpp \
    source/win32/NstIoStream.hpp \
    source/win32/NstIoWave.hpp \
    source/win32/NstMain.hpp \
    source/win32/NstManager.hpp \
    source/win32/NstManagerAviConverter.hpp \
    source/win32/NstManagerBarcodeReader.hpp \
    source/win32/NstManagerCheats.hpp \
    source/win32/NstManagerDipSwitches.hpp \
    source/win32/NstManagerEmulator.hpp \
    source/win32/NstManagerFds.hpp \
    source/win32/NstManagerFiles.hpp \
    source/win32/NstManagerFrameClock.hpp \
    source/win32/NstManagerHelp.hpp \
    source/win32/NstManagerImageDatabase.hpp \
    source/win32/NstManagerImageInfo.hpp \
    source/win32/NstManagerInesHeader.hpp \
    source/win32/NstManagerInput.hpp \
    source/win32/NstManagerLanguage.hpp \
    source/win32/NstManagerLauncher.hpp \
    source/win32/NstManagerLogfile.hpp \
    source/win32/NstManagerMachine.hpp \
    source/win32/NstManagerMovie.hpp \
    source/win32/NstManagerNetplay.hpp \
    source/win32/NstManagerNsf.hpp \
    source/win32/NstManagerPaths.hpp \
    source/win32/NstManagerPathsFilter.hpp \
    source/win32/NstManagerPreferences.hpp \
    source/win32/NstManagerRecentDirs.hpp \
    source/win32/NstManagerRecentFiles.hpp \
    source/win32/NstManagerSaveStates.hpp \
    source/win32/NstManagerSound.hpp \
    source/win32/NstManagerSoundRecorder.hpp \
    source/win32/NstManagerTapeRecorder.hpp \
    source/win32/NstManagerVideo.hpp \
    source/win32/NstObjectBackup.hpp \
    source/win32/NstObjectDelegate.hpp \
    source/win32/NstObjectHeap.hpp \
    source/win32/NstObjectPod.hpp \
    source/win32/NstResourceBitmap.hpp \
    source/win32/NstResourceClipboard.hpp \
    source/win32/NstResourceCursor.hpp \
    source/win32/NstResourceFile.hpp \
    source/win32/NstResourceGeneric.hpp \
    source/win32/NstResourceIcon.hpp \
    source/win32/NstResourceMenu.hpp \
    source/win32/NstResourceString.hpp \
    source/win32/NstResourceVersion.hpp \
    source/win32/NstString.hpp \
    source/win32/NstSystemAccelerator.hpp \
    source/win32/NstSystemDll.hpp \
    source/win32/NstSystemGuid.hpp \
    source/win32/NstSystemInfo.hpp \
    source/win32/NstSystemKeyboard.hpp \
    source/win32/NstSystemRegistry.hpp \
    source/win32/NstSystemThread.hpp \
    source/win32/NstSystemTime.hpp \
    source/win32/NstSystemTimer.hpp \
    source/win32/NstWindowCustom.hpp \
    source/win32/NstWindowDialog.hpp \
    source/win32/NstWindowDropFiles.hpp \
    source/win32/NstWindowDynamic.hpp \
    source/win32/NstWindowGeneric.hpp \
    source/win32/NstWindowMain.hpp \
    source/win32/NstWindowMenu.hpp \
    source/win32/NstWindowParam.hpp \
    source/win32/NstWindowPoint.hpp \
    source/win32/NstWindowRect.hpp \
    source/win32/NstWindowStatusBar.hpp \
    source/win32/NstWindowUser.hpp \
    source/unrar/unrar.h \
    source/7zip/IArchive.h \
    source/7zip/IProgress.h \
    source/7zip/IStream.h \
    source/7zip/MyUnknown.h \
    source/7zip/PropID.h \
    source/7zip/Types.h \
    source/kaillera/kailleraclient.h \
    source/win32/resource/QNestopia.rc

DISTFILES += \
    source/core/database/NstDatabase.xml \
    source/win32/resource/copying.zip \
    source/win32/resource/FolderClosed.bmp \
    source/win32/resource/FolderOpen.bmp \
    source/win32/resource/application.ico \
    source/win32/resource/application_j.ico \
    source/win32/resource/fds.ico \
    source/win32/resource/nes.ico \
    source/win32/resource/nes_j.ico \
    source/win32/resource/nsf.ico \
    source/win32/resource/nsf_j.ico \
    source/win32/resource/unf.ico \
    source/win32/resource/unf_j.ico \
    source/win32/resource/window.ico \
    source/win32/resource/window_j.ico \
    source/win32/resource/gun.cur \
    source/win32/resource/nestopia.manifest
